CREATE TABLE `T_SIMPLE_NOTIFICATION` (
  `ID` int NOT NULL AUTO_INCREMENT COMMENT '提示表',
  `FROM_ID` varchar(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '来自',
  `AIM_ID` varchar(36) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '送达',
  `TIP_CODE` varchar(36) DEFAULT NULL COMMENT '消息类型',
  `STATE` int DEFAULT NULL COMMENT '0发送1已读2删除',
  `CONTENT` varchar(36) DEFAULT NULL COMMENT '内容',
  `CREATE_TIME` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=112 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC;